version: '3'
services:
  web:
    build: ./docker/php
    ports:
      - "1337:80"
    volumes:
      - "./web:/var/www/html"
      - "./lib:/var/www/lib"
      - "./config/conf.d/pdo.ini:/usr/local/etc/php/conf.d/custom.ini"
      - "./vendor:/var/www/vendor"

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=testing